### ISSUE TITLE
instrukcje są niejasne

### ISSUE THREAD

**Issue by xKubsoneQ** [Jacob1Tm/Connect-Health#1]
instrukcje są niejasne, mój serwer zepsuł się przez ten plugin.

**Comment by Jacob1Tm** [comment]
mało informacji

**Comment by xKubsoneQ** [comment]
dodalem plugin na moj serwer minecraft, teraz przestal dzialac, usunela sie cala mapa, do tego teraz moj monitor wariuje, pomoz mi

**Comment by Jacob1Tm** [comment]
nice
